<?php

//use yii\helpers\Html;
//use yii\grid\GridView;

// untuk export
use yii\widgets\Pjax;
use kartik\export\ExportMenu;

// grid view (tabel)
use kartik\grid\GridView;
use kartik\helpers\Html;

//---- datepicker untuk tanggal,buat
use dosamigos\datepicker\DatePicker;

/* @var $this yii\web\View */
/* @var $searchModel frontend\models\BarangSearch */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title = 'Barang';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="barang-index">

    <h1><?= Html::encode($this->title) ?></h1>
    <?php // echo $this->render('_search', ['model' => $searchModel]); ?>

    <p>
        <?php
		/*= Html::a('Create Barang', ['create'], ['class' => 'btn btn-success']) 
		*/?>
    </p>
    <?php /*= GridView::widget([
        'dataProvider' => $dataProvider,
        'filterModel' => $searchModel,
        'columns' => [
            ['class' => 'yii\grid\SerialColumn'],

            'kode_barang',
            'kategori',
            'nama_barang',
			'tanggal',
            'kondisi_barang',

            [
			'class' => 'yii\grid\ActionColumn',
			'template' => '{view} {update}',
			],
        ],
    ]); */?>
	
	<?php // Export list?>
  
	<?php $gridColumns = [
		'kode_barang',
        'kategori',
        'nama_barang',
		'tanggal',
        'kondisi_barang',
	];?>
	
	<?php Pjax::begin(); ?>
	<?php
		$fullExportMenu = ExportMenu::widget([
			'dataProvider' => $dataProvider,
			'filterModel' => $searchModel,
			'columns' => $gridColumns,
			'target' => ExportMenu::TARGET_BLANK,
			'fontAwesome' => false, // bisa ubah true atau false (bawaan mah true)
			'pjaxContainerId' => 'kv-pjax-container',
			'filename' 		=> 'Barang'. '_' . date('Y-m-d_H-i-s'),
			'exportConfig' 	=> [
				ExportMenu::FORMAT_TEXT => false,
				ExportMenu::FORMAT_PDF => false,
				ExportMenu::FORMAT_CSV => false,
				ExportMenu::FORMAT_HTML => false,
			]
			
		]);
		
		echo GridView::widget([
			'dataProvider' => $dataProvider,
			'filterModel' => $searchModel,
			'columns' => [
				['class' => 'kartik\grid\SerialColumn'],
					
					'kode_barang',
					'kategori',
					'nama_barang',
					'tanggal',
					'kondisi_barang',
				
				[
					'class' => 'kartik\grid\ActionColumn', 
					'template' => '{view} {update}',
					
				],
				
			],
			'pjax' => true,
			'pjaxSettings' => ['options' => ['id' => 'kv-pjax-container']],
			'panel' => [
				'type' => GridView::TYPE_PRIMARY,
				'heading' => '<h3 class="panel-title"><i class="glyphicon glyphicon-list-alt"></i> Barang</h3>',
				'before' => '', //bisa di isi
				'after' => false,
				'showFooter' => false,
			],
			// set a label for default menu
			
			'export' => [
				'label' => 'Export EXCEL',
				'fontAwesome' => false, // bisa ubah true atau false (bawaan mah true),
				'PDF' => [
					'options' => [
						'title' => 'barang',
						'subject' => 'barang',
						'author' => 'barang',
						'keywords' => 'NYCSPrep, preceptors, pdf',
						'showHeader' => false,
				'showFooter' => false,
					]
				],
			],
			'exportConfig' => [
				GridView::CSV => [
					'label' => 'Save as CSV',
					'filename' 		=> 'Barang'. '_' . date('Y-m-d_H-i-s'),
				],
				GridView::EXCEL => [
					'label' => 'Save as EXCEL',
					'filename' => 'Barang'. '_' . date('Y-m-d_H-i-s'),
					'options' => [
						'title' => 'barang',
						'showFooter' => false,
					], 
				],
				GridView::PDF => [
					'label' => 'Save as PDF',
					'filename' 		=> 'Barang'. '_' . date('Y-m-d_H-i-s'),
					'showFooter' => '<font color = "40E0D0">dolores</font>',
					'options' => [
						'title' => 'barang',
					],  
					'config' => [
						'mode' => 'c',
						'format' => 'A4-P',
						'destination' => 'D',
						'marginTop' => 20,
						'marginBottom' => 20,
						'methods' => [
                            'SetHeader' => [
								$this->title,
								['odd' => $this->title, 'even' => $this->title]
                            ],
							'SetFooter' => [
                                ['odd' => 'abcd', 'even' => 'efg']
                            ],
                        ],
						'options' => [
							'title' => $this->title,
							'subject' => Yii::t('kvgrid', 'PDF export generated by kartik-v/yii2-grid extension'),
							'keywords' => Yii::t('kvgrid', 'krajee, grid, export, yii2-grid, pdf')
						],
						'contentBefore'=>'',
						'contentAfter'=>''
                    ]
				],
			],
			// your toolbar can include the additional full export menu
			'toolbar' => [
				'{export}',
				$fullExportMenu,
				/*
				['content'=>
					Html::button('<i class="glyphicon glyphicon-plus"></i>', [
						'type'=>'button', 
						'title'=>Yii::t('kvgrid', 'Add Book'), 
						'class'=>'btn btn-success'
					]) . ' '.
					Html::a('<i class="glyphicon glyphicon-repeat"></i>', ['jumlahbrg'], [
						'data-pjax'=>2, 
						'class' => 'btn btn-default', 
						'title'=>Yii::t('kvgrid', 'Reset Grid')
					])
				],
				*/
			]
		]);
 
	?>
	<?php Pjax::end(); ?>
</div>
